### ISSUE TITLE
過剰な暴力表現の表示間違い

### ISSUE THREAD

**Issue by tetraface** [malaybaku/VMagicMirror#1001]
v3.4.0でVRM 1.0のファイルを読み込んだ時、「過剰な暴力表現」のOK/NG表示が実際のデータ内のものと異なっています。他のパラメータの値が誤って適用されているように思います。

**Comment by malaybaku** [comment]
@tetraface 

ご連絡ありがとうございます。該当部分について、誤って「過剰な性的表現」のライセンスに基づいた表示を行っていたことを確認しました。

#1004 で修正済みのため、次のリリースにて修正版が公開されます。
