### ISSUE TITLE
Shortcuts for Enabling Gamepad/VMC

### ISSUE THREAD

**Issue by codemakura** [malaybaku/VMagicMirror#1052]
Would it be possible to add assignable keyboard shortcuts for turning the Gamepad On/Off, Enabling/Disabling VMC Protocol, and maybe one for Calibration? It'd be great to be able to switch these on & off while other windows/software is open without having to tab back to VMagicMirror!! Thank you as always 😋💖

**Comment by malaybaku** [comment]
#1054 is released as v3.8.3, so I close this issue.
