### ISSUE TITLE
リップシンクの初期化

### ISSUE THREAD

**Issue by neight0903** [malaybaku/VMagicMirror#22]
OSSのissue報告が初めてですので、使い方に誤りがあれば申し訳ございません。

# 概要
発話中にリップシンクのチェックボックスを外すと口が空いたままになります。

# 頻度
必ず発生

# 解決方針
現在動作環境を構築できないのでGitHub上でコードを確認させていただいたところ、AnimMorphEasedTarget.csのL64辺りで判定を行っていそうでしたので、そちらに初期化処理を記載すると解決しそうです。

**Comment by malaybaku** [comment]
fixed on v0.8.1
