### ISSUE TITLE
透過モード時に画面が縦に伸びてしまう

### ISSUE THREAD

**Issue by malaybaku** [malaybaku/VMagicMirror#348]
## 概要

透過モード時、ウィンドウ上部のバーのぶんだけ画面が単純にY方向に引き伸ばされてしまう。
この結果、キャラが歪んで表示される。

直近の回避方法

- あらかじめウィンドウをデカくしてアバターを小さく映すことで歪みをおさえる
- そもそも透過にしない

## 対応指針

以下どっちかを行う。どっちもWin32API和解コース

- 透過モード時、論理的にはウィンドウバーが残った状態をキープする
- 透過モード時、引き伸ばしを考慮してUnity側で逆に絵をちょっとY方向に縮めて保証する

**Comment by kirurobo** [comment]
（的外れだったらすみません。）
UniWinApiでは、ウィンドウのバーを変更があった際、ウィンドウサイズ変更（大きさの数値はその時点のサイズと等しいまま）のイベントを発生させるようにしてました。
https://github.com/kirurobo/UniWinApiAsset/blob/f4395eb6fa64e24505bfcee139ac1722c6866d42/Scripts/UniWinApi.cs#L575

**Comment by malaybaku** [comment]
リサイズイベントを呼ぶ方針で直りました！
PR上で2つに分かれてしまってますが、#350 と #351 で以下のように修正しました。

- 透過/非透過の切り替え直後にリサイズイベントを呼ぶ
- リサイズは「ちょっとだけサイズを変えて元に戻す」という形で呼び出し
    - これは、サイズをまったく変更しない実装のとき、透過→非透過の切り替え時に画面がヨコに潰れてしまう問題がたまに発生したためです
