### ISSUE TITLE
ひじIKが一部のアバターで悪さしているっぽい

### ISSUE THREAD

**Issue by malaybaku** [malaybaku/VMagicMirror#369]
## 概要

ぼんやりユーザー報告見てると上がってるので明記だけ…

## 対応指針

- 手元のモデルで再現できてない+モデラーさんからは指摘来ないため、ボーンの微妙な初期曲げとかに由来する問題な気がする。
- 良いモデル情報が来たら対応検討する。
- Muscleによる脇の開き制御が現実的かどうかは検討余地あるかも

**Comment by pete-orchards** [comment]
獏星さん、はじめまして。大変お世話になっています。ピート(石雲緋糸)といいます。

ひじIKの問題に関して、自分のアバターで歪みが生じた例と、生じない例の両方に遭遇しています。
「ひじIKの悪さ」は以下のようなものでしょうか↓
https://youtu.be/Bz00Bu1_9us?t=1918

以下がこれまで経験した事象です。
◇石雲緋糸モデル(https://hub.vroid.com/characters/276993304730066075/models/4103495745278343675)において、
・blenderにてAポーズでモデルを作成し、fbxで出力。
・unityで読み込みTポーズ化する際に、[VRM0]->[Freeze T-Pose]、あるいはVRM Exporterウインドウでの[Make T-Pose]でポーズ修正したモデルが、VMagicMirrorで読み込んだ際に肘が身体の中心側に歪む。
・blenderにてTポーズに修正してからfbx出力してunityに読み込んだ時には、肘の歪みは起こらなかった。blenderでは腕関係ではShoulder、Armと各Fingerボーンを回転してポーズ修正したのみで、Forearmボーンの調整はしていない。
・unity内でAnimator Controllerでポーズチェックをしたり、VRoidHubの3Dプレビューなどでは同様のひじIKの事象は見られていません。
・unityのVRM Exporterウインドウでの[Make T-Pose(unity internal)]でポーズ修正した場合、上記の[Make T-Pose]とは別の結果になる。歪んだ場合と歪まなかった場合があったかと思うが、記憶が曖昧かつ詳細に検証していない。
・ひじの歪み方は、最初に貼ったURLのおすしモデルの場合と同様です。

◇おすしモデル(https://hub.vroid.com/characters/3834479663535935512/models/5111515627748104447)において、
・blenderにてTポーズでモデルを作成し、fbxで出力。
・モデルv1.x台の時にはひじの歪みは発生していなかったが、v2.xにアップデートした際に歪みが発生。
・共通して上記VRM Exporterウインドウでの[Make T-Pose]を使用してからVRMに出力。
・v2.x制作時にボーンを修正したかは未確認(作業者が違うため)。

個人的感想としては、配信時には基本的にバストアップのみ映すので、ひじが歪んでいても許容範囲でした。
また現在VMagicMirror内の設定にある[脇をしめる強さ]等では調整する方向が違うため、修正できませんでした。


もし対応検討されるようでしたら、モデルの各バージョンの.vrmや.fbxなどありますので、検証用としてデータ提供可能です。
また必要な情報等ありましたら回答致します。
曖昧な情報が多く申し訳ありませんが、参考になれば幸いです。
よろしくお願いいたします。

**Comment by malaybaku** [comment]
VRM 1.0対応の過程で(恐らく)肘ねじれの性質が変わって再発したため、一旦こちらをクローズして立て直します。
