### ISSUE TITLE
UniVRM 1.0対応

### ISSUE THREAD

**Issue by malaybaku** [malaybaku/VMagicMirror#383]
## 概要

VRM 1.0への対応です。

少なくとも表情の排他について、モデル側が設定すべき事をモデル側の責務にしないといけないよね、という話です。

…とは思うんだけど、例えば「じゃあリップシンク続行オプションはGUIに載り続けるのは破壊的か？」というと破壊的じゃない気がするので、UniVRM 1.0より十分遅れて機能をDeprecatedにするのでもいいかも。

万が一UniVRM本体の動きが怪しかった場合だけ要検討。

**Comment by malaybaku** [comment]
指針と想定する主要な差分を追記。

指針:

- 移行期の存在に配慮して、同一レポジトリからVRM 0.xと1.0に対して別々のビルドを吐けるようにするのが良さそう。つまり、Standard/FullとVRM 0.x/1.0で計4つのビルドを吐けるように準備すべき。
    - WPFはコード変更のみ
    - Unityは少なくともコード+UPMの変更になるので若干ヤバそう

想定される主要な差分:

- 表情のClipにOverrideがつく: WPF/Unity両方で、パーフェクトシンク以外の表情処理の全てに影響するはず
- Constraint: ほぼUnityのみが要対応で、使われ方によっては危険そう。(ヒジをFBBIKのBend Goalで設定しているのとかが良くないかも)

**Comment by Unihedro** [comment]
👍

**Comment by malaybaku** [comment]
Close as staled issue / created new issue #833 instead.
