### ISSUE TITLE
Receive input from non-GUI/WPF以外からの入力受付

### ISSUE THREAD

**Issue by malaybaku** [malaybaku/VMagicMirror#446]
Support non-GUI input to swap avatar etc.

Should consider before implement:

- Support hotkey or not
- Messaging style
- Whether GUI-equivalent message set is enough or not
- Risk the GUI indication becomes incorrect

ref: https://twitter.com/xisumavoid/status/1321008802884427776

**Comment by th3pooka** [comment]
Oh! Thank you for considering this idea!
I would use this process to change my avatar on my streaming. I have several different outfits for my character and change it manually. If this is even possible, I will have to see if Twitch can talk to the program and switch the avatar for me when the chat uses the right command.
I don't have any programming background, so I don't think I can help with the creation of any code. But i am very interested in this feature.

**Comment by malaybaku** [comment]
Plan:

- GUI process (WPF) supports non-GUI input by option.
- For the first version, supports following commands only
    - Load model, with local file path (without license check)
    - Setting file load, with file path
- This support leads model license check skip, so:
    - Before enabling this option, GUI shows warning about model license management
    - Does not support VRoid SDK based model load automation

**Comment by malaybaku** [comment]
Implemented in #446 and above PR in WPF, https://github.com/malaybaku/VMagicMirrorConfig/pull/143 .

Available in v1.6.2.
