### ISSUE TITLE
Request: Constant effect from held keys.

### ISSUE THREAD

**Issue by EatThePath** [malaybaku/VMagicMirror#469]
If you are streaming a game, in many cases just a flash when pressing a key is not great for showing inputs. For games where keys are frequently held down, having an effect start when the key is pressed and end when released would be very appreciated.

I have some experience with C# unity coding myself, so if this is not implemented but there is no particular reason it shouldn't be, I may take a shot at adding it myself. I file this anyway in case it's a particularly easy one to add.

**Comment by malaybaku** [comment]
@EatThePath 
Thank you for request.

The behavior you have pointed has historical reason that, I wanted to avoid unclarity about key up/down flag management reliability.

However the app now seems enough stable, so I will try it in the next version's update.

I will also try to make the avatar's hands are down during key pressed.

**Comment by malaybaku** [comment]
As #480 was merged to develop branch, this update will be included in v1.6.0 release.
