### ISSUE TITLE
Meshes disappear when triggering blendshapes on some old GPUs

### ISSUE THREAD

**Issue by emilianavt** [malaybaku/VMagicMirror#470]
Hi!

Due to a [bug in Unity](https://issuetracker.unity3d.com/issues/the-build-does-not-fallback-to-cpu-skinning-when-has-directx-has-feature-level-10-dot-1-or-lower), on certain old GPUs meshes can disappear when blendshapes are activated. This happens because [GPU skinning](https://docs.unity3d.com/ScriptReference/PlayerSettings-gpuSkinning.html) requires compute shaders and Unity fails to fall back to CPU skinning. It mostly happens with old integrated Intel graphics, like Intel HD Graphics 3000 from 2011.

I heard today VMagicMirror is affected by this Unity bug as well. The result can look like this:
![unknown](https://user-images.githubusercontent.com/38952746/99818176-2d286e80-2b4e-11eb-84dc-23439ddab54f.png)

It can be resolved by either building with Unity 2019.4.12f1 or newer, or disabling GPU skinning.

**Comment by malaybaku** [comment]
@emilianavt 
Hi!

Thank you for report, I am aware of this problem but did not know the background so it is very helpful.

In develop branch I already have updated Unity version to 2019.4.14f1 by #467 , so the problem will be solved.

I will close the issue when the next version is released.

**Comment by malaybaku** [comment]
close with v1.6.0 release.
