### ISSUE TITLE
Microphone Not Working

### ISSUE THREAD

**Issue by DemonRem** [malaybaku/VMagicMirror#471]
hey @malaybaku the microphone not working i see there is not volument activity in the program , but i check my microphone and he working just fine

**Comment by malaybaku** [comment]
@DemonRem 
Cannot reproduce and I need further information. 

Please share:

- Windows OS version
- Microphone device name
- VMagicMirror version

Also I want to confirm what "volument activity" means,

- Does volume visualization and sensitivity adjust UI (in v1.5.0a) work?
- If volume visualization works, then specific model cause the problem, or any models can reproduce same problem?
- If you have several microphones, then do all of them reproduce same problem?

**Comment by DemonRem** [comment]
Windows OS Version : Windows 10 Pro
Mic Device Name is : Skiller SGH2 Headset
VMagicMirror 1.5.0
____________________________________________

the issue is that the model not sync his lips with my voice however i see the volume under the lips sync bar that its moving

**Comment by malaybaku** [comment]
Then it might be VRM model setup problem, 

> If volume visualization works, then specific model cause the problem, or any models can reproduce same problem?

Please check it, especially if your VRM is exported from non-VRM model.

**Comment by DemonRem** [comment]
yea i check it its was my model
