### ISSUE TITLE
Zip file is broken

### ISSUE THREAD

**Issue by dann1kid** [malaybaku/VMagicMirror#475]
I had try download latest version and its can not unzipping =/

**Comment by malaybaku** [comment]
@dann1kid 
Not reproduced. It seems rather internet (or BOOTH server) issue than software itself.

Please try this link, the same file as BOOTH:
https://drive.google.com/drive/folders/1cnd1RtqR6HNBo6uMKaa5N4gzKv8Ndq_I?usp=sharing

**Comment by dann1kid** [comment]
Thank you for answer. I have tried on different computers, and browsers, but it still remains when download from official site. I think  it depends on internet control system. GD link works.  ¯\_(ツ)_/¯
