### ISSUE TITLE
一定時間入力が無い場合は手を下ろす機能

### ISSUE THREAD

**Issue by PermanentWave** [malaybaku/VMagicMirror#476]
(誤操作でタイトルがわかりにくくてすみません)
初めまして。デスクトップマスコットとして便利に使用させていただいております。

要望ですが、一定時間入力が無い場合は手を下ろす機能をお願いできないでしょうか。
一度キーボードを触ると入力無くともずっとキーボードに手を添えていてなんとなく違和感を感じました。

ご検討よろしくお願いします。

**Comment by malaybaku** [comment]
検討します。
が、根本的には該当ケースで手がピタッと止まっている事が問題な気もするので、手を下ろす以外の解決方法も考えます。

12月中のリリースバージョンに入れられるか自信ないため、Milestoneは設けません。

**Comment by PermanentWave** [comment]
返信ありがとうございます。
ご対応よろしくお願いします。

**Comment by malaybaku** [comment]
#495 でdevelopマージ済みのため、次リリース(v1.6.1)で搭載されます。

**Comment by PermanentWave** [comment]
twitterのデモ映像拝見いたしました。ご対応いただきありがとうございました。
