### ISSUE TITLE
FPSの最大値を制限出来る機能を追加してほしい

### ISSUE THREAD

**Issue by yahagi-day** [malaybaku/VMagicMirror#542]
現状のVMagicMirrorはモニターのリフレッシュレートと同期したFPSで動作しています。
なので高リフレッシュレートモニターを使用した場合FPSが上昇しGPU使用率が無視できない程度には上昇します。
VMagicMirrorはゲーム実況などで高負荷なゲームと同時に動かすことが多いのでFPSリミッター機能を追加して欲しいです。
![image](https://user-images.githubusercontent.com/32870950/116347692-a330b000-a827-11eb-8819-965d3662cda3.png)

**Comment by malaybaku** [comment]
あくまで予定ですが、設定ウィンドウのEffectタブにFPS半減のオン/オフ設定を追加して下記のように対策します。

- QualityでVery LowまたはLowを選択している場合、もともとVSync Countが`Don't Sync`を想定しているため、FPS半減の設定は影響を受けません。
- QualityでMedium以上を選択している場合、FPS半減のオン/オフに基づいてVSync Countが`Every Second V Blank`または`Every V Blank`相当の状態になります。

**Comment by malaybaku** [comment]
#544 で上記コメントの方針に沿ってdevelopブランチにマージされたため、v1.7.0のリリース時点で対応済みとなります。

※手元の60HzモニターでFPSが60/30に切り替わるのを確認して #544 をマージとしています。144Hzモニター等でも同様に動作するはずですが、v1.7.0で明らかに直っていなければ再度このissueをOpenして下さい。
