### ISSUE TITLE
Face tracking from Webcam not working

### ISSUE THREAD

**Issue by intrepidOlivia** [malaybaku/VMagicMirror#576]
Hello. I am looking forward to using this software, it is better than many others. But I don't know how to enable face tracking. Even though my webcam appears in the list, nothing happens when I select it. The avatar's head doesn't move when my head moves. But I know my webcam works, I can use it in other apps. This is not listed in the troubleshooting page, are there any steps I can do to troubleshoot?

I am on Windows version 10.0.19043 Build 19043
My webcam is Logitech C920s

Thank you!

**Comment by intrepidOlivia** [comment]
User error! I'm a noob. I had another application using the camera, and so this application wasn't able to access the video feed.

**Comment by ShadowMax** [comment]
> User error! I'm a noob. I had another application using the camera, and so this application wasn't able to access the video feed.

My webcam tracking not working too! 
How did you find out which application is preventing you from using your webcam? 
What was the name of that application?

**Comment by ShadowMax** [comment]
> My webcam tracking not working too! How did you find out which application is preventing you from using your webcam? What was the name of that application?
Problem was in my android webcam emulator program, I just switch it to another app.
