### ISSUE TITLE
Need some help

### ISSUE THREAD

**Issue by MinervaGa** [malaybaku/VMagicMirror#580]
i have a problem, my cpu is crap and obs or streamlabs take a lot to load and constantly crash, it would be reallly apreciated if you could put the older versions with the virtual camera enabled y really like this program but my pipi-pupu cpu doesnt like obs at all
(sorry for the shity english)

**Comment by malaybaku** [comment]
Hi @MinervaGa ,

Sorry for late response.
Please try v1.4.0 from the link below (*this link is temporary)

https://drive.google.com/drive/folders/16IIVKWXfqpujuny4PbpKfIxuRpQSHDz2?usp=sharing
