### ISSUE TITLE
脱FinalIK

### ISSUE THREAD

**Issue by malaybaku** [malaybaku/VMagicMirror#630]
Animation RiggingのIKでも今Final IKでやってる事ができるのでは…という改修です。

OSSであるからには導入必須の有償アセットを減らしたい、という意味において注力すべきタスクです。

- 見栄えに対するプラスはあまり期待できません。
- Script Execution Orderにも影響するけど影響は小さいはず…。

**Comment by kuochiyoug** [comment]
BioIK はどうでしょうか？
非常につかいやすいと思いますが

**Comment by malaybaku** [comment]
ご提案ありがとうございます。
が、以下の理由からBioIKはひとまず採用対象ではありません。

- 有償アセットを減らすのが目的であり、OSSとUnity自体の機能のみを検討対象としている
- Animation Riggingは今回の置き換えに十分堪えるはず

Animation Riggingの機能不足があった場合は改めて検討させていただきます。(とは言え、その場合でも有償アセットから別の有償アセットへの乗り換えは望ましくないと思っていますが…)

**Comment by malaybaku** [comment]
本件アクセサリー機能のリリースを優先してv2.0.0で対応しなかったため、milestoneをいったん無しにして優先度も少し下げます.

**Comment by malaybaku** [comment]
close as stale issue.
