### ISSUE TITLE
Feature Request: Accessory Attach to World/Absolute Positioning

### ISSUE THREAD

**Issue by NinaKawakami** [malaybaku/VMagicMirror#702]
Accessories are a very useful feature but there is no attachment setting for "world", so for now, it's impossible to place unmoving accessories (such as a desk), they are always bound to a place on the avatar's body. "Attach to: world" would be an incredibly useful feature for prop placement
![VMagicMirrorConfig_Z40YPfivHp](https://user-images.githubusercontent.com/42161067/149391120-b0b23ee5-44cb-4464-8a57-4c6f13a55af9.png)
.

**Comment by malaybaku** [comment]
@NinaKawakami 
In #706 `World` option has been added, so the update will be available in next version (v2.0.1). 

I close this issue as the repository's workflow, but please wait for a while until the release.
