### ISSUE TITLE
VMagic Mirror Config is being Suspended.

### ISSUE THREAD

**Issue by Gravitium** [malaybaku/VMagicMirror#721]
## Problem Description
I have installed VMagic Mirror yesterday and couldn't make it work. The menu doesn't launch only the model viewer. 

Except for one time today when I change the graphic settings of the application to High Performance GPU, but after closing it the problem came back and would not open again even when it is set to the GPU.

![image](https://user-images.githubusercontent.com/69876104/152114247-01310c83-dd88-4a41-b7b6-020769b29635.png)
![image](https://user-images.githubusercontent.com/69876104/152210056-9cb8834a-243e-4f3e-9c82-f491dc861d95.png)
## Computer Specification

Device: Acer Predator Helios 300 PH315-52-54KC
OS: Windows 11 64bit
CPU: Intel Core i5 9300H
GPU: 6GB RTX2060
RAM: 16 Gb

( not sure if this is needed but here )
Mic: Fifine K669B
Webcam: None

Also I have 2 antivirus: IObit Anti-Malware and Avast not sure of these affect the start up but I think not since it nothing about the application being stopped by them in the logs.

## Misc

I don't have any proof that it worked since it only happened one time and I was too excited and used it on a call with friends but one of my friends has screenshot on discord of me using it via OBS virtual cam.

![unknown](https://user-images.githubusercontent.com/69876104/152117643-d76cb8d6-f70a-4d8e-90ab-0cbd7e83aded.png)

**Comment by malaybaku** [comment]
@Gravitium 
Hi sorry for late reply.
It seems to be an software environment dependent problem.

- Please try to reset settings to default, to check whether the setting content is the cause.
    - https://malaybaku.github.io/VMagicMirror/en/questions#vmagicmirror-stops-soon-after-started
- Please confirm anti-virus software do not bad things by following steps. As far as I know, there are some anti-virus that prevents VMagicMirror to start, or even deletes app runtime files (exe/dll).
    - Disable anti-virus
    - Uninstall and Reinstall VMagicMirror and run it several times

**Comment by Gravitium** [comment]
@malaybaku 
Thank you for the reply, I am not able to reset the settings since the control panel does not appear. 
I also tried uninstalling and installing it again but to no avail. I disabled my anti-virus software and run the program but the control panel still doesn't open. I have repeated this process several times. If nothing really helps, I think maybe using an older version might work but I am unsure where to download older versions from.

**Comment by malaybaku** [comment]
@Gravitium 

>  I am not able to reset the settings since the control panel does not appear.
Please see here about how to reset setting, the actual process is NOT on the control panel. Here reset means just deleting file  on the file explorer before starting VMagicMirror.

https://malaybaku.github.io/VMagicMirror/en/questions#vmagicmirror-stops-soon-after-started

About older version, please try v1.8.2. This version is the latest version of non-installer based style exe, so it might produce different result.
Note that some of help page's content is incorrect for this version.

https://drive.google.com/drive/folders/1RIgF7h-OylW6cE9ljBZG0Gnm1P9-QXKZ?usp=sharing

**Comment by Gravitium** [comment]
Indeed I deleted the file but nothing happened. Thank you i'll try if the previous version works

**Comment by Gravitium** [comment]
@malaybaku 
Thank you so much it worked first try.
![image](https://user-images.githubusercontent.com/69876104/153163177-1bdd755e-c510-4695-9cd5-e742bdd93868.png)
