### ISSUE TITLE
モーションや表情の実行中だけアクセサリーを表示したい

### ISSUE THREAD

**Issue by malaybaku** [malaybaku/VMagicMirror#722]
まあ必要だよな…とは思っていた機能改善です。

- Word to Motion機能に入れるのはストレートフォワードな気がする
- 表情スイッチにも需要ありそうだが、複雑そうならいったん飛ばしてもOK
- アクセサリーの表示基準はORで決まる。つまり、以下どちらかを満たせばアクセサリーが表示される。
    - アクセサリータブで有効にしている = 従来挙動
    - Word to Motionまたは表情スイッチの実行中に、実行中アイテムによって指定されたアクセサリーである

追記

- この機能とアニメーション画像アクセサリの相性を考慮すると、アニメーション画像アクセサリは再表示したときに`time=0`扱いにリセットすることが望ましいはず。現状そうなってなければ、ついでに直す。

**Comment by Gravitium** [comment]
@malaybaku 

I forgot to ask yesterday. where we could get non-installer based style exe of the newer version if you upload them?

**Comment by malaybaku** [comment]
@Gravitium ,

Here is not the correct place to discuss it, I replied in #721.

**Comment by malaybaku** [comment]
The feature will be released in v2.0.2.
