### ISSUE TITLE
Feature Requests: add support for use TIFA

### ISSUE THREAD

**Issue by GalaxyOfZero** [malaybaku/VMagicMirror#730]
it would be amazing if that were possible if you could use Tifa with VMagicMirror that would make a lot of things more fun.
https://melonspeedruns.itch.io/tifa

**Comment by malaybaku** [comment]
@GalaxyOfZero 
Thanks for request, but I do not plan for support it.

Based on my development policy, VMagicMirror very rarely support communication with other applicarion or services. It is to keep app's simplicity.
Currently VMagicMirror supports communication with iFacialMocap, but is a kind of exception.

This is also the reason I do not support standardized protocol like VMC Protocol/OSC.
