### ISSUE TITLE
Game Capture is black/not working in OBS. No avatar shows.

### ISSUE THREAD

**Issue by phourniner** [malaybaku/VMagicMirror#738]
I'm not certain what's going on, but trying to put this as a Source in OBS is not playing nicely with VMagicMirror.

Here are the steps:

1. I set up my avatar the way I want it in the VMagicMirror program. The program works fine by itself, no issues there.
2. Enter OBS, set up a Game Capture to capture the VMagicMirror.exe window as described in the tutorial on your website. (no preview of the game capture shows up during this either)
3. The Source shows up as a small red dot in the top left on the OBS preview screen, trying to drag that red dot results in it disappearing. When previewing the source, it is just a black screen. When clicking the source in the list, and hovering over the preview screen in OBS, the mouse cursor is just two arrows (the drag cursor)

I'm not sure what's going on. On a fresh install of OBS on a different computer, this Game Capture works perfectly.

**Comment by malaybaku** [comment]
I close this issue as a duplication of #755
