### ISSUE TITLE
are there any texture layouts?

### ISSUE THREAD

**Issue by Zanzancomms** [malaybaku/VMagicMirror#775]
would like to know how the texture layouts are for the pen, tablet, keys and other things, just see the gamepad one in the change textures tip https://malaybaku.github.io/VMagicMirror/tips/change_textures is hard to do with just try and error, without exact sizes

**Comment by Zanzancomms** [comment]
also a way to keep the position, rotation and scale of the models you import in the accessories tab, it always goes back to the floor when i start the program again, and is a hassle to edit the position of the model in importing in my editing software every time i want to move it

**Comment by malaybaku** [comment]
@Zanzancomms 
Sorry for very late response,

- I have updated pen UV and it is available since current newest version (v2.0.5).
    - https://malaybaku.github.io/VMagicMirror/en/tips/change_textures/
- Tablet and keys texture works almost as simple sprite, so there are no texture layouts.
