### ISSUE TITLE
VMagicMirror Will Not Appear on my Game Capture Anymore

### ISSUE THREAD

**Issue by Avrielf** [malaybaku/VMagicMirror#786]
Not even a day goes by. I was streaming yesterday, and my avatar was there. Today it isn't. I am using the app StreamlabsOBS. Why did it stop working?

**Comment by Avrielf** [comment]
I used window capture instead, and it shows, but now it has a black background. How do I get rid of the black background?

**Comment by malaybaku** [comment]
@Avrielf 
For a workground, please try to:

- Disable semi-transparent object and effect like shadow, keyboard etc. 
- Use chromakey to remove background in OBS. If Bloom effects disturbs chromakey to work correctly, disable it from VMagicMirror's Setting Window > Effect tab, by setting Bloom intensity to 0.

I cannot answer why game capture fails exactly, though downgrading OBS to older version might solve issue.

**Comment by malaybaku** [comment]
Close as stale issue.
