### ISSUE TITLE
missing the ability to send/receive OSC/VMC tracking data tp/from other software such as VSeeFace, Unity/ etc

### ISSUE THREAD

**Issue by ArcherLeagcy64** [malaybaku/VMagicMirror#804]

**Comment by Zanzancomms** [comment]
would be nice to have this, to track the mouse/tablet and keyboard inputs and send them to other apps, to make up for only having face tracking

**Comment by KannaCrossing** [comment]
OSC/VMC support would be greatly appreciated. Facial tracking via webcam is better on other software so having vmagicmirror for just mouse/keyboard/gamepad tracking and having others for the other stuff would be great.
