### ISSUE TITLE
カスタムモーション再生終了時に一瞬だけスタンバイポーズに戻る際のジャンプカットがあります。

### ISSUE THREAD

**Issue by ShihikoStudios** [malaybaku/VMagicMirror#805]
カスタムアニメーション作っている途中気づいたことです。バグじゃないですが、モーション終わってからスタンドバイに戻る時にトランジションをスムーズに変化出来たら良さそうです。

It is noticible when creating custom motions, but it is not a bug. At the end of a custom motion animation there is a jump cut between the end of the motion and returning the vrm model to the standby pose. It would be good if this transition can be smoothed out.

このスナップバックみたいのモーションは最近のうなずき、首を振ると拍手には無さそうです。そこはヒントかになるかもしれない。

This snap back animation at the end of custom motions does not occurr for the new built in nodding, shaking and clapping motions. So this maybe a hint if there is a difference in implementation.

**Comment by formulynx** [comment]
同じ問題が原因になっているかもしれませんが、
待機モーションを有効化しているときのゲームパッドの挙動が、
・カスタムモーション中はゲームパッドは同じ周期で動き続ける
・ビルドインモーション中はゲームパッドを置いたかのように移動が止まり、終了時にジャンプして手に戻る
ような挙動になっております。

現状では終了時の挙動としてはゲームパッドはカスタムモーションの方が自然に見えますが、
再生中にフワフワと浮いているのが違和感あるようであれば、ビルドインモーション時の挙動プラス
再生終了時にスムーズに手に戻ってくるのがベターかなと思いました。

**Comment by malaybaku** [comment]
@ShihikoStudios @formulynx 
ご報告ありがとうございます、こちらは #835 で対策してv2.0.10としてリリースされました。
