### ISSUE TITLE
Glossy Effect Issue/Eyes, Blinking Not Happening 

### ISSUE THREAD

**Issue by xxsmokyquartz** [malaybaku/VMagicMirror#850]
_Alright, um i don't understand why this is occurring but when i ever i move my characters mouth to speak or to display an expression on her this off putting glossy effect appears out of the blue, and i have went to unity already to check on the shaders she has on her right after i imported her to a vrm file; removed the fancy new shaders the plugin i downloaded had on it to make this vrm model work out since she was ported to mmd to pmx file for i can add the clothing, hair etc,, i put her everything of her in place, and ported her into blender then unity. (edited)

that's when i decided to check her out, and the effect appeared right away, i already messed with vmagic mirror effect option to see if maybe it's the shadow or the bloom that is doing it but nope, none. even when i get her in unity, she doesn't have this glossy effect - also when i put her into mmd - nothing. i don't know why this is only happening with her. (my other models dont get this effect at all)
i also noticed that she refuses to blink and move her eyeballs..i did double check on unity before i ported her that her eyes moved, and blinking was good - it was fine but when i apply it to use it on vmagic mirror nothing occurs. 

here is the screenshot for the gloss issue; https://imgur.com/oFOU0J2 and just encase, here is some other screenshots containing the settings for the set up i have on vmagic mirror to even unity as well on her shaders - heck i will even put up a screenshot of how she appears on mmd to pmx editor; https://imgur.com/a/D7aPtEz stash of the screenshots if you want more detail please just ask away, and i will reply back. 
any help would be great_

**Comment by malaybaku** [comment]
close as staled issue
