### ISSUE TITLE
Rest position control

### ISSUE THREAD

**Issue by porkyoot** [malaybaku/VMagicMirror#855]
Hello, I have issues with the rest position as my model is quite round and the arms clip into the body when resting. There don't seem to have an option for movement constraints or arm colision in VRM.
Here's the example :
![armclip-bug01](https://user-images.githubusercontent.com/85759819/198863778-d7b6313d-0d57-42fe-9209-617b03a63e66.png)
I would like to be able to control the angle of the arms at rest. Thanks in advance.

**Comment by malaybaku** [comment]
@porkyoot 
I merged #887 to support rest position control feature in next version (v3.0.2), so I close the issue.

If you feel the feature is not enough, please re-open the issue or create a new one.
