### ISSUE TITLE
サムネイルが存在しないVRM 1.0のモデルのロード時に例外が発生する

### ISSUE THREAD

**Issue by saturday06** [malaybaku/VMagicMirror#878]
サムネイルが存在しないVRM 1.0のモデルのロード時に例外が発生するようです。

再現モデル
[material1.zip](https://github.com/malaybaku/VMagicMirror/files/10318005/material1.zip)

動作環境
- VMagicMirror v3.0.1 Standard Edition
- Windows 11 10.0.22621 ビルド 22621

スクリーンショット

<img width="500" alt="スクリーンショット 2022-12-29 155250" src="https://user-images.githubusercontent.com/532872/209914903-9f9d35ca-a58b-49f6-8db1-54a00978149b.png">

**Comment by saturday06** [comment]
VRMコンソーシアムのサンプルモデルでも再現しました
https://github.com/vrm-c/vrm-specification/blob/ce5b58cb0882206e4759e34e77c3875f43e61659/samples/VRMC_materials_mtoon_UV_Animation_Test/vrm/VRMC_materials_mtoon_UV_Animation_Test.vrm

**Comment by malaybaku** [comment]
@saturday06 
ご連絡ありがとうございます。

VRMコンソーシアムのモデルにて手元でも再現が確認でき、対策を行いました。
この修正は次バージョン(v3.0.2)でリリースされます。

#882
