### ISSUE TITLE
Dvorak配列を使用時、アバターが打鍵するキーの位置が違う

### ISSUE THREAD

**Issue by JapanYoshi** [malaybaku/VMagicMirror#884]
デバイスの表示＞キーボード・タッチパッド　がONの場合、Windowsのキーボード配列がQWERTY以外だと、実際に打鍵した物理的キーではなく、QWERTY配列だと同じ文字に割り当てられるキーがハイライトされます。

正しい挙動の例：QWERTYでもDvorakでも1列に並んだ数字キーを順番に入力
[vmm_good.webm](https://user-images.githubusercontent.com/8707990/211187341-0a675673-c7a7-4772-a77c-bb1617bf16c1.webm)

誤った挙動の例：Dvorakでは1列に並んだ文字キー（AOEUIDHTNS）を順番に入力
[vmm_bad.webm](https://user-images.githubusercontent.com/8707990/211187346-db85ee4a-5288-4540-85df-3dd7951ea1a3.webm)

こう表示されるべき：QWERTYにおけるASDFGHJKL;を順番に入力
[vmm_please.webm](https://user-images.githubusercontent.com/8707990/211187351-156e4491-b4f7-4eec-95e1-c6c33c21dc35.webm)

ちなみに、[Unityのスクリプトリファレンス](https://docs.unity3d.com/ja/2022.1/ScriptReference/KeyCode.html)では、既定の設定だと`Event.keyCode`は既定では物理キーコードを返すはずと書いてあります。InputManagerのUse Physical KeysがONになっているかチェックしていただきたいです。

**Comment by malaybaku** [comment]
@JapanYoshi 
起票ありがとうございます。

が、QWERTY配列以外に対応する予定は現時点ではありません。
類似の報告を日本語以外のキーボード環境のユーザーからも指摘されていますが、同様に取り下げています。

背景としては

1. 修正方針が具体的に立っていない
2. 現行実装はキーボード配列のバリエーションに対してかなり柔軟性を欠いており、直すのに時間がかかると思っている
3. 個人的に優先度が低いつもりでいる

事などがあります。1について、VMagicMirrorでは打鍵検出でUnityの入力システムを使っていない(打鍵の検出は下記コードのうちキーボード入力に関する部分で行っている)ため、InputManagerの設定は効果がないと考えています。

https://github.com/malaybaku/VMagicMirror/blob/master/VMagicMirror/Assets/Baku/VMagicMirror/Scripts/InputMonitoring/KeyAndMouseInput/RawInputChecker.cs

個人的に優先度が低いと考えていることも踏まえ、本件について更に掘り下げる場合、調査結果の追加共有あるいはPRの作成をご検討下さい。

**Comment by JapanYoshi** [comment]
using Linearstar.Windows.RawInput;
    using Linearstar.Windows.RawInput.Native;

ネットを検索しても`Linearstar.Windows.RawInput`のドキュメンテーションが見つからないので掘り下げられません。推測するところ、`RawInputKeyboardData.GetKeyCode()`の返り値が、実装ミスで物理キーのキーコードではないのか、それか、物理キーコードを返す関数が他にあるのかだと思います。

Unityに実装されているキー入力をわざわざ違うライブラリーで実装されたのはどうしてでしょうか？
