### ISSUE TITLE
VRoidStudio 1.20.0でVRM1.0として出力したモデルの瞳が変な方向を向いてしまう

### ISSUE THREAD

**Issue by malaybaku** [malaybaku/VMagicMirror#897]
ユーザー報告、かつ手元で再現した。
目ボーンの動き方を1%とかまで縮めても再現するため、ユーザーがVMMの設定で回避することはできない。

要調査だが、VMMの実装で目ボーンについては仮想ボーンを無視して直接制御しているのが原因の可能性が高め。

**Comment by FujiSunflower** [comment]
Unity2020.3.33f1でUniVRM-0.108.0_e16dで出力したアバターで同様の現象がありました。
![image](https://user-images.githubusercontent.com/20571538/222688164-f9276ce5-474a-4507-8516-38a1526b489a.png)

**Comment by FujiSunflower** [comment]
本来は片眼鏡のアバターなのですが、めり込んでいる？ような現象もありました。
![image](https://user-images.githubusercontent.com/20571538/222688646-a9daef01-227e-428e-ab0c-189772b3ebe3.png)
![image](https://user-images.githubusercontent.com/20571538/222688865-d30d96af-5cc1-4653-958f-93045e2f56f7.png)

**Comment by malaybaku** [comment]
@FujiSunflower 情報ありがとうございます。

本現象ですが、さしあたってVMMの実装のなかで

> 目ボーンのローカルxyz軸がTポーズ時にワールド軸のxyz軸と一致している

という前提(=VRM0.x相当の前提)で目を操作するコードがあることで起こっている可能性が高く、調査中です。

関連事象の候補としてはVRoidStudio v1.20.0に由来する何かである可能性もあったのですが、上記のご報告や手元でのGazeの挙動検証などを踏まえて、あくまでVMMの動作の不具合であると判断しています。

https://twitter.com/vroid_pixiv/status/1631209033448423426

**Comment by FujiSunflower** [comment]
どうやらエディタからVRM1.0の出力時にControlRigがAnimatorのHumanoidAvatarに入るらしく、結果的にはGetComoponent<Animator>().getBoneTransform()を行ったものがVRM0.0想定で動かせるという記述がありますね。
https://vrm-c.github.io/UniVRM/ja/vrm1/vrm1_controlrig.html

**Comment by malaybaku** [comment]
#900 で対策したため、v3.0.3以降のリリースで対策されます。

本レポジトリではビルドリリース時ではなくdevelopブランチへのマージ時点でissueをcloseしているので、本issueもこの時点でcloseします。
