### ISSUE TITLE
Some parts of model loading in incorrect places

### ISSUE THREAD

**Issue by violetgynoid** [malaybaku/VMagicMirror#906]
When using VMagicMirror, but not any other VRM-loading software, the head and attached parts are not loading in the correct position and are instead loading with a strange offset.

![image](https://user-images.githubusercontent.com/29111040/226710922-815229ed-a908-4892-87d5-a5696cb1e6aa.png)

Is there a console or log file I can search for to gain more information about why this is loading incorrectly, or any optimizations that need to be made model-side?

**Comment by violetgynoid** [comment]
It seems that any part with blendshapes is loading at the root instead of the proper position. How can I fix this?

**Comment by malaybaku** [comment]
@violetgynoid thanks for contact and sorry for late response,

I think of some points which might be the cause, but not sure. Current version of VMM does not output detailed log file about this issue.

- VRM 1.0 support implement in VMM does something wrong
- meshes' origin is somehow treated incorrectly
- VMM is more aggressive to update all blendshape values than other apps, and it might lead the issue

If you can reproduce this issue in a model that allows redistribution for debug-purpose, please consider sharing it with me.

**Comment by malaybaku** [comment]
close as staled issue
