### ISSUE TITLE
Upon loading a VRM 1.0 model, the eyes are cross-eyed.

### ISSUE THREAD

**Issue by ThePlayerZero** [malaybaku/VMagicMirror#908]
On the latest version of VMagicMirror, when you load a VRM 1.0 model, the eyes will load cross-eyed.

![image](https://user-images.githubusercontent.com/68795576/228458271-48d3878a-61bf-4189-863b-de6d82f985cb.png)

![image](https://user-images.githubusercontent.com/68795576/228457652-1effd079-1683-4469-a49d-8837329d7e1f.png)

![image](https://user-images.githubusercontent.com/68795576/228457839-a1b2e101-6797-4d78-b7b3-dfd29b51558f.png)

**Comment by malaybaku** [comment]
@ThePlayerZero 
Thanks, it is the same issue as #897 and the fix has been released today (v3.1.0).

**Comment by ThePlayerZero** [comment]
Sorry for the dupe then cuz I didn't see it! But thank you!
