### ISSUE TITLE
サブディスプレイにウィンドウを置くと再起動時に位置が記憶されない

### ISSUE THREAD

**Issue by 1nagawa** [malaybaku/VMagicMirror#933]
デスクトップマスコット用途に楽しく使わせていただいています。

メインディスプレイに配置すると他ウィンドウの操作の邪魔になってしまうため、サブディスプレイに配置しようと思ったのですが、アプリを再起動するとウィンドウがメインディスプレイに戻ってきてしまいます（※サブディスプレイ上の座標を見つけられずメインディスプレイに戻ってる？ようにも見えます）。
可能なら、サブディスプレイ上の座標を記憶して再配置されるよう修正いただければと思います。

別件で、これは不具合ではありませんが「アプリアイコンを通知領域に収納する」オプション（常駐アプリによくある物）があると、誤って×ボタンで閉じてしまうことがなくデスクトップマスコットとしてより便利なので、そういった機能の実装もご検討いただければと思います。

**Comment by malaybaku** [comment]
@1nagawa 

詳細ありがとうございます。

> アプリを再起動するとウィンドウがメインディスプレイに戻ってきてしまいます

手元環境でも再現することを確認しました。想定外挙動であるため、調査します。


> アプリアイコンを通知領域に収納する

こちらは実装上のコストを踏まえて検討しますが、優先度はあまり高くないことをご了承下さい。

**Comment by malaybaku** [comment]
@1nagawa 

> アプリを再起動するとウィンドウがメインディスプレイに戻ってきてしまいます

の問題について #940 で本問題が発生しにくくなるよう対策したため、次回のアップデートで改善されます。

またアプリアイコンを残す処置については要望のissueとして別で追加した( #938 )ため、本issueはcloseします。
