### ISSUE TITLE
SpoutかNDIの対応

### ISSUE THREAD

**Issue by kogoto3** [malaybaku/VMagicMirror#934]
機能追加の要望です。

OBSでVMMを使うにあたってぜひとも欲しい機能。合わせて設定画面で出力解像度を指定できると助かります。
簡単に調べた感じでは「Spout4Unity」よりも「KlakSpout」というプラグインのほうが安定しているそうです？

**Comment by malaybaku** [comment]
要望ありがとうございます。
対応する場合はSpoutを少なくとも対応します(実装コストによっては両方とも同時に対応します)。

主に負荷関連での懸念があり、最優先すべきユースケースとは考えていないため、直近のアップデートまでに必ずしも対応しない可能性があるのをご了承下さい。

**Comment by malaybaku** [comment]
v3.2.1でSpoutに対応したためcloseします。
