### ISSUE TITLE
視線に対して顔の上下角の補正

### ISSUE THREAD

**Issue by kogoto3** [malaybaku/VMagicMirror#936]
VRMの表現に関する要望です。

目線が正面を見るようにカーソルを移動させたとき現在は少し顔を上げた角度になっていますが、設定画面にてこれを上下にプラスマイナスに角度補正できると嬉しいです。

プラス数値を指定して見下ろす感じにすれば尊大な態度のキャラを演出できますし、マイナス数値を指定して下からのぞき込むような根暗な三白眼キャラを演出できるなど、表現の幅が広がると思います。

**Comment by malaybaku** [comment]
返信滞ってすみません、

VMagicMirrorでは当該機能をサポートする予定はありません。これはオプションの粒度が私が想定するのより細かいと考えているためです。

ソフト自体ではなくVMCP (VMC Protocol)の受信対応の一環で実現可能になる可能性があります( #804 )が、このissueとしてはcloseします。
