### ISSUE TITLE
マウス操作時やキーボード操作時の意図しない動作

### ISSUE THREAD

**Issue by kogoto3** [malaybaku/VMagicMirror#937]
不具合？の報告です。

マウスクリックやキーボードのキーを押しっぱなしにしていても、カーソルの移動等他に操作がなければしばらくしてアイドル判定になり腕を下げてしまう。

**Comment by malaybaku** [comment]
> マウスクリックやキーボードのキーを押しっぱなしにしていても、カーソルの移動等他に操作がなければしばらくしてアイドル判定になり腕を下げてしまう。

こちらは意図した挙動であり、不具合ではありません。

現時点での想定品質としてはエッジケース的であり、対応しない予定です。ご了承下さい。
