### ISSUE TITLE
Android external tracking support

### ISSUE THREAD

**Issue by t0msk** [malaybaku/VMagicMirror#956]
Hello,

Im coming here from VUP (they ceased project) so I was looking for another Vtuber software, I see that you support tracking by phone (to offload some tasks from CPU, I was using it too), but it is only for iOS, and I have no iOS, I have only Android, so I would like ask you could you port it to Android please?

**Comment by malaybaku** [comment]
Thanks for the feedback,

I do not have plan to support some specific Android apps.

Instead, I am now working to support VMCP (VMC Protocol) receive feature. This will result to support Android apps with VMCP sending feature.

I close this issue. Please see #804 's status for VMCP support status.
