### ISSUE TITLE
[Bug] Custom motion files for the Word to Motion feature are read from VMagicMirror_Dev_Files for v3.3.1_Full

### ISSUE THREAD

**Issue by will-yama** [malaybaku/VMagicMirror#990]
# 種類
バグ

# 概要
v3.3.1_Full にて、Word to Motion機能の設定で読み込まれるカスタムアニメーションの参照先が `VMagicMirror_Dev_Files/Motions` になっています。
ドキュメントにて、読み込まれる先が`VMagicMirror_Files\Motions`とのことです。

https://malaybaku.github.io/VMagicMirror/tips/use_custom_motion/
> v1.9.0以降: (マイドキュメント)\VMagicMirror_Files\Motions

# 再現手順

1. アニメーションファイルを`\VMagicMirror_Files\Motions`内に配置します
![bugexplain0](https://github.com/malaybaku/VMagicMirror/assets/10701638/51824fec-c7e9-46b6-a227-3f2026d0b799)
2. v3.3.1 Full EditionのVMagicMirrorを起動する
3. `ホーム` タブの`詳細設定`メニューから`設定ウィンドウを開く` を選択します
![bugexplain1](https://github.com/malaybaku/VMagicMirror/assets/10701638/5c191b04-70da-4095-90e6-5b34682a3914)

4. 左メニューからWord to Motionのアイコンを選択し、適当なキー割り当てモーションの歯車アイコンをクリックします
![bugexplain2](https://github.com/malaybaku/VMagicMirror/assets/10701638/6a901370-2613-4b23-a9f9-09b3245fe65a)

5. `カスタムモーション`を選択して、`モーション`のドロップダウンをクリックします

→現象発生：アニメーションファイルが表示されない
![bugexplain3](https://github.com/malaybaku/VMagicMirror/assets/10701638/fcd4c92a-b438-4953-8ebf-ff42671cf9a6)

# 回避方法

1. アニメーションファイルを`VMagicMirror_Dev_Files/Motions` 内に配置します
![bugexplain4](https://github.com/malaybaku/VMagicMirror/assets/10701638/ddd7e37f-21ae-4a3c-9cd1-93a9b4063db5)
2. VMagicMirrorを再起動します
3. 上記の再現手順3～5を行って、`モーション`のドロップダウンをクリックすると、カスタムモーションのファイルが読み込まれます
![bugexplain5](https://github.com/malaybaku/VMagicMirror/assets/10701638/846809d3-1145-40e0-8a31-50be94a01d12)

# English Summary
In VMagicMirror v3.3.1, Custom motion files are read from `VMagicMirror_Dev_Files/Motions` instead of `VMagicMirror_Files\Motions`. This affects the **Word to Motion** feature, where users can set a custom animation from a drop-down that is populated from files within the `Motion` folder.
This bug can be temporarily avoided by placing the animation files under `VMagicMirror_Dev_Files/Motions` instead of `VMagicMirror_Files\Motions`.

**Comment by malaybaku** [comment]
@will-yama 
Thanks for feedback and detail.

The issue is caused by Unity version update. Fix PR is #991 so next release will work correctly.

**Comment by malaybaku** [comment]
I close this issue, since v3.4.0 is released to fix the issue.

**Comment by will-yama** [comment]
Thank you for the very quick fix!
