### ISSUE TITLE
Accesories no longer work after going to full version

### ISSUE THREAD

**Issue by HugoVG** [malaybaku/VMagicMirror#993]
[bug affects v3.3.1]
using the free version(3.3.1) accesories work fine
using the paid version(3.3.1) accesories will not spawn in the world cannot be rotated or positioned

paid version(3.3.0) works fine

files are placed in the same directory, both same files

**Comment by malaybaku** [comment]
@HugoVG 
Thanks for feedback, 

The issue has the same cause as #990 and Unity version update leads that problem.

#991 is the fix, so next version will work correctly.

**Comment by malaybaku** [comment]
I close this issue, since v3.4.0 is released to fix the issue.
