### ISSUE TITLE
VMMへのお問い合わせにつきまして

### ISSUE THREAD

**Issue by kabakism** [malaybaku/VMagicMirror#994]
お世話になっております。
2週間ほど前にBoothの方に、VMMへのお問い合わせをお送りしておりますが、
ご確認いただいておりますでしょうか？
また、次に記載がありましたお問い合わせ先のTwitter(X)のDMも先日、お送りしております。

当方、Githubでの連絡が不慣れなため、上記にてご返信をいただけると助かりますが、
こちらでのご対応が都合が良いようでしたら再掲いたしますのでその旨ご連絡いただければ幸いです。

**Comment by malaybaku** [comment]
該当すると思われるメッセージに返信したためcloseしました
